# This container returns only a redirect for satayo.guide to satayo entry page
# docker build -t docker-si.wuerth-phoenix.com/satayo-userguide-unprivileged:latest -f Dockerfile.satayo .
# docker run -it --rm -p8080:8080 docker-si.wuerth-phoenix.com/satayo-userguide-unprivileged:latest
FROM docker.io/nginxinc/nginx-unprivileged:alpine@sha256:26b5d4920434bc4d8c17a68201488cf4b3d2391f0d25305cdfe66ccdc6d18aa4

COPY satayo/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

USER nginx

EXPOSE 8080
